spaces = ' '*25
print('%s Unit 7, 10-14 Clyde Street,' % spaces)
print('%s Surrey Hills,' % spaces)
print('%s VIC 3127' % spaces)
print()
print()
print('Dear Me,')
print()
print('Just reminding me that,')
print('I create my personal abundance from an infinite source')
print('and also that,')
print('the core of my being is my ultimate source.')
print()
print('Many blessings and much love and light,')
print('Thubten Noryang')